"""Builds and initializes manual.md -- the single running document that
combines every screenshot with a plain-language explanation of what's on
it. render_manual_section is pure (takes a facts dict, returns markdown
text), so it's unit-testable without a browser.
"""
import os


def render_manual_section(title, url, screenshot_rel_path, facts):
    """Builds a manual-style markdown section from a collect_page_facts()
    dict. The screenshot is embedded inline via markdown image syntax so
    it renders directly in the same document as its explanation, right
    below the URL and above the Where/What-you-can-do breakdown."""
    lines = [
        f"## {title}",
        "",
        f"**URL:** `{url}`",
        "",
        f"![{title}]({screenshot_rel_path})",
        "",
    ]

    looking_at = []
    if facts["charts"]:
        for c in facts["charts"]:
            looking_at.append(f'- A {c["type"]} titled "{c["title"]}"')
    if facts["table_columns"]:
        looking_at.append("- A table with columns: " + ", ".join(facts["table_columns"][:20]))
    if looking_at:
        lines.append("**What you're looking at**")
        lines.append("")
        lines.extend(looking_at)
        lines.append("")

    can_do = []
    if facts["export_labels"]:
        formats = []
        for l in facts["export_labels"]:
            formats.append(l.split("(", 1)[1].split(")", 1)[0] if "(" in l and ")" in l else l)
        can_do.append("- **Export/save:** " + " or ".join(formats))
    if facts["other_labels"]:
        can_do.append("- **Other actions:** " + ", ".join(facts["other_labels"]))
    if facts["date_filter_count"]:
        can_do.append(f"- **Date filter:** filter this view by a date range ({facts['date_filter_count']} control(s))")
    if facts["dropdown_labels"]:
        can_do.append("- **Dropdown filters:** " + ", ".join(facts["dropdown_labels"]))
    if facts["filterable_column_count"]:
        can_do.append(f"- **Column filters:** {facts['filterable_column_count']} column(s) can be filtered/searched")
    if facts["pagination"]:
        note = "- **Pagination:**"
        if facts["pagination"]["total_pages"]:
            note += f" {facts['pagination']['total_pages']} pages"
        if facts["pagination"]["page_size"]:
            note += f", {facts['pagination']['page_size']}"
        can_do.append(note)
    if can_do:
        lines.append("**What you can do here**")
        lines.append("")
        lines.extend(can_do)
        lines.append("")

    if not looking_at and not can_do:
        lines.append("_No interactive controls or data visualizations detected._")
        lines.append("")

    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def init_manual(out_dir):
    """Starts manual.md fresh so old sections don't accumulate across runs."""
    os.makedirs(out_dir, exist_ok=True)
    try:
        with open(os.path.join(out_dir, "manual.md"), "w", encoding="utf-8") as f:
            f.write("# Auto-generated Dashboard Manual\n\n")
            f.write("Generated by C2M DocGen. Each section below corresponds to one screenshot, "
                     "shown inline below its explanation.\n\n---\n\n")
    except Exception as e:
        print("failed to initialize manual.md:", e)


def append_section(out_dir, title, url, screenshot_rel_path, facts):
    manual_path = os.path.join(out_dir, "manual.md")
    try:
        with open(manual_path, "a", encoding="utf-8") as f:
            f.write(render_manual_section(title, url, screenshot_rel_path, facts))
    except Exception as e:
        print("failed to append manual section:", e)
